[2025-02-20T06:56:03.475+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-20T06:56:03.551+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: finprode8_v2_etl_dag.extract_task manual__2025-02-20T06:55:58.427423+00:00 [queued]>
[2025-02-20T06:56:03.581+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: finprode8_v2_etl_dag.extract_task manual__2025-02-20T06:55:58.427423+00:00 [queued]>
[2025-02-20T06:56:03.583+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-02-20T06:56:03.620+0000] {taskinstance.py:2890} INFO - Executing <Task(SparkSubmitOperator): extract_task> on 2025-02-20 06:55:58.427423+00:00
[2025-02-20T06:56:03.627+0000] {standard_task_runner.py:72} INFO - Started process 5434 to run task
[2025-02-20T06:56:03.635+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', '***_v2_etl_dag', 'extract_task', 'manual__2025-02-20T06:55:58.427423+00:00', '--job-id', '63', '--raw', '--subdir', 'DAGS_FOLDER/***_v2_etl_dag.py', '--cfg-path', '/tmp/tmpr_6k6qfo']
[2025-02-20T06:56:03.639+0000] {standard_task_runner.py:105} INFO - Job 63: Subtask extract_task
[2025-02-20T06:56:03.810+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.9/site-packages/airflow/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-20T06:56:03.935+0000] {task_command.py:467} INFO - Running <TaskInstance: finprode8_v2_etl_dag.extract_task manual__2025-02-20T06:55:58.427423+00:00 [running]> on host ***-airflow-scheduler
[2025-02-20T06:56:04.151+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ratih malini' AIRFLOW_CTX_DAG_ID='***_v2_etl_dag' AIRFLOW_CTX_TASK_ID='extract_task' AIRFLOW_CTX_EXECUTION_DATE='2025-02-20T06:55:58.427423+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-20T06:55:58.427423+00:00'
[2025-02-20T06:56:04.156+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-20T06:56:04.297+0000] {base.py:84} INFO - Retrieving connection 'spark_main'
[2025-02-20T06:56:04.301+0000] {spark_submit.py:474} INFO - Spark-Submit cmd: spark-submit --master spark://***-spark-master:7077 --packages org.postgresql:postgresql:42.2.18 --name arrow-spark /spark-scripts/***_v2_extract.py
[2025-02-20T06:56:07.929+0000] {spark_submit.py:641} INFO - :: loading settings :: url = jar:file:/home/airflow/.local/lib/python3.9/site-packages/pyspark/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2025-02-20T06:56:08.059+0000] {spark_submit.py:641} INFO - Ivy Default Cache set to: /home/airflow/.ivy2/cache
[2025-02-20T06:56:08.061+0000] {spark_submit.py:641} INFO - The jars for the packages stored in: /home/airflow/.ivy2/jars
[2025-02-20T06:56:08.077+0000] {spark_submit.py:641} INFO - org.postgresql#postgresql added as a dependency
[2025-02-20T06:56:08.079+0000] {spark_submit.py:641} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-e4dd3ab7-3f0f-4173-8056-380f20cb3a49;1.0
[2025-02-20T06:56:08.081+0000] {spark_submit.py:641} INFO - confs: [default]
[2025-02-20T06:56:08.220+0000] {spark_submit.py:641} INFO - found org.postgresql#postgresql;42.2.18 in central
[2025-02-20T06:56:08.244+0000] {spark_submit.py:641} INFO - found org.checkerframework#checker-qual;3.5.0 in central
[2025-02-20T06:56:08.260+0000] {spark_submit.py:641} INFO - :: resolution report :: resolve 178ms :: artifacts dl 5ms
[2025-02-20T06:56:08.262+0000] {spark_submit.py:641} INFO - :: modules in use:
[2025-02-20T06:56:08.264+0000] {spark_submit.py:641} INFO - org.checkerframework#checker-qual;3.5.0 from central in [default]
[2025-02-20T06:56:08.266+0000] {spark_submit.py:641} INFO - org.postgresql#postgresql;42.2.18 from central in [default]
[2025-02-20T06:56:08.267+0000] {spark_submit.py:641} INFO - ---------------------------------------------------------------------
[2025-02-20T06:56:08.268+0000] {spark_submit.py:641} INFO - |                  |            modules            ||   artifacts   |
[2025-02-20T06:56:08.270+0000] {spark_submit.py:641} INFO - |       conf       | number| search|dwnlded|evicted|| number|dwnlded|
[2025-02-20T06:56:08.271+0000] {spark_submit.py:641} INFO - ---------------------------------------------------------------------
[2025-02-20T06:56:08.272+0000] {spark_submit.py:641} INFO - |      default     |   2   |   0   |   0   |   0   ||   2   |   0   |
[2025-02-20T06:56:08.273+0000] {spark_submit.py:641} INFO - ---------------------------------------------------------------------
[2025-02-20T06:56:08.274+0000] {spark_submit.py:641} INFO - :: retrieving :: org.apache.spark#spark-submit-parent-e4dd3ab7-3f0f-4173-8056-380f20cb3a49
[2025-02-20T06:56:08.275+0000] {spark_submit.py:641} INFO - confs: [default]
[2025-02-20T06:56:08.278+0000] {spark_submit.py:641} INFO - 0 artifacts copied, 2 already retrieved (0kB/5ms)
[2025-02-20T06:56:08.608+0000] {spark_submit.py:641} INFO - 25/02/20 06:56:08 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-02-20T06:56:10.716+0000] {spark_submit.py:641} INFO - Traceback (most recent call last):
[2025-02-20T06:56:10.718+0000] {spark_submit.py:641} INFO - File "/spark-scripts/***_v2_extract.py", line 54, in <module>
[2025-02-20T06:56:10.720+0000] {spark_submit.py:641} INFO - extract()
[2025-02-20T06:56:10.721+0000] {spark_submit.py:641} INFO - File "/spark-scripts/***_v2_extract.py", line 21, in extract
[2025-02-20T06:56:10.723+0000] {spark_submit.py:641} INFO - config = load_config()
[2025-02-20T06:56:10.724+0000] {spark_submit.py:641} INFO - File "/spark-scripts/***_v2_extract.py", line 14, in load_config
[2025-02-20T06:56:10.726+0000] {spark_submit.py:641} INFO - with open(config_file, "r") as json_file:
[2025-02-20T06:56:10.726+0000] {spark_submit.py:641} INFO - FileNotFoundError: [Errno 2] No such file or directory: 'config.json'
[2025-02-20T06:56:10.800+0000] {spark_submit.py:641} INFO - 25/02/20 06:56:10 INFO ShutdownHookManager: Shutdown hook called
[2025-02-20T06:56:10.802+0000] {spark_submit.py:641} INFO - 25/02/20 06:56:10 INFO ShutdownHookManager: Deleting directory /tmp/spark-2e83d519-a17a-4e20-9a77-e049f8da1732
[2025-02-20T06:56:10.883+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 177, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 567, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://***-spark-master:7077 --packages org.postgresql:postgresql:42.2.18 --name arrow-spark /spark-scripts/***_v2_extract.py. Error code is: 1.
[2025-02-20T06:56:10.913+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=***_v2_etl_dag, task_id=extract_task, run_id=manual__2025-02-20T06:55:58.427423+00:00, execution_date=20250220T065558, start_date=20250220T065603, end_date=20250220T065610
[2025-02-20T06:56:10.973+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-20T06:56:10.976+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 63 for task extract_task (Cannot execute: spark-submit --master spark://***-spark-master:7077 --packages org.postgresql:postgresql:42.2.18 --name arrow-spark /spark-scripts/***_v2_extract.py. Error code is: 1.; 5434)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 177, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 567, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://***-spark-master:7077 --packages org.postgresql:postgresql:42.2.18 --name arrow-spark /spark-scripts/***_v2_extract.py. Error code is: 1.
[2025-02-20T06:56:11.013+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-20T06:56:11.033+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
