[2025-02-20T15:46:36.539+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-20T15:46:36.671+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: finprode8_v2_etl_dag.extract_task manual__2025-02-20T15:46:32.551269+00:00 [queued]>
[2025-02-20T15:46:36.713+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: finprode8_v2_etl_dag.extract_task manual__2025-02-20T15:46:32.551269+00:00 [queued]>
[2025-02-20T15:46:36.715+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-02-20T15:46:36.775+0000] {taskinstance.py:2890} INFO - Executing <Task(SparkSubmitOperator): extract_task> on 2025-02-20 15:46:32.551269+00:00
[2025-02-20T15:46:36.799+0000] {standard_task_runner.py:72} INFO - Started process 403 to run task
[2025-02-20T15:46:36.810+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', '***_v2_etl_dag', 'extract_task', 'manual__2025-02-20T15:46:32.551269+00:00', '--job-id', '86', '--raw', '--subdir', 'DAGS_FOLDER/***_v2_etl_dag.py', '--cfg-path', '/tmp/tmpfp6scpg4']
[2025-02-20T15:46:36.824+0000] {standard_task_runner.py:105} INFO - Job 86: Subtask extract_task
[2025-02-20T15:46:37.033+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.9/site-packages/airflow/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-20T15:46:37.157+0000] {task_command.py:467} INFO - Running <TaskInstance: finprode8_v2_etl_dag.extract_task manual__2025-02-20T15:46:32.551269+00:00 [running]> on host ***-airflow-scheduler
[2025-02-20T15:46:37.521+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ratih malini' AIRFLOW_CTX_DAG_ID='***_v2_etl_dag' AIRFLOW_CTX_TASK_ID='extract_task' AIRFLOW_CTX_EXECUTION_DATE='2025-02-20T15:46:32.551269+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-20T15:46:32.551269+00:00'
[2025-02-20T15:46:37.527+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-20T15:46:37.632+0000] {base.py:84} INFO - Retrieving connection 'spark_main'
[2025-02-20T15:46:37.635+0000] {spark_submit.py:474} INFO - Spark-Submit cmd: spark-submit --master spark://***-spark-master:7077 --packages org.postgresql:postgresql:42.2.18 --name arrow-spark /spark-scripts/***_v2_extract.py
[2025-02-20T15:46:42.287+0000] {spark_submit.py:641} INFO - :: loading settings :: url = jar:file:/home/airflow/.local/lib/python3.9/site-packages/pyspark/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2025-02-20T15:46:42.480+0000] {spark_submit.py:641} INFO - Ivy Default Cache set to: /home/airflow/.ivy2/cache
[2025-02-20T15:46:42.483+0000] {spark_submit.py:641} INFO - The jars for the packages stored in: /home/airflow/.ivy2/jars
[2025-02-20T15:46:42.489+0000] {spark_submit.py:641} INFO - org.postgresql#postgresql added as a dependency
[2025-02-20T15:46:42.491+0000] {spark_submit.py:641} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-d36a42ef-4843-4694-8d99-f8de5bd45dd8;1.0
[2025-02-20T15:46:42.493+0000] {spark_submit.py:641} INFO - confs: [default]
[2025-02-20T15:46:45.292+0000] {spark_submit.py:641} INFO - found org.postgresql#postgresql;42.2.18 in central
[2025-02-20T15:46:45.925+0000] {spark_submit.py:641} INFO - found org.checkerframework#checker-qual;3.5.0 in central
[2025-02-20T15:46:46.232+0000] {spark_submit.py:641} INFO - downloading https://repo1.maven.org/maven2/org/postgresql/postgresql/42.2.18/postgresql-42.2.18.jar ...
[2025-02-20T15:46:47.874+0000] {spark_submit.py:641} INFO - [SUCCESSFUL ] org.postgresql#postgresql;42.2.18!postgresql.jar (1935ms)
[2025-02-20T15:46:48.168+0000] {spark_submit.py:641} INFO - downloading https://repo1.maven.org/maven2/org/checkerframework/checker-qual/3.5.0/checker-qual-3.5.0.jar ...
[2025-02-20T15:46:48.516+0000] {spark_submit.py:641} INFO - [SUCCESSFUL ] org.checkerframework#checker-qual;3.5.0!checker-qual.jar (639ms)
[2025-02-20T15:46:48.517+0000] {spark_submit.py:641} INFO - :: resolution report :: resolve 3446ms :: artifacts dl 2581ms
[2025-02-20T15:46:48.519+0000] {spark_submit.py:641} INFO - :: modules in use:
[2025-02-20T15:46:48.519+0000] {spark_submit.py:641} INFO - org.checkerframework#checker-qual;3.5.0 from central in [default]
[2025-02-20T15:46:48.520+0000] {spark_submit.py:641} INFO - org.postgresql#postgresql;42.2.18 from central in [default]
[2025-02-20T15:46:48.521+0000] {spark_submit.py:641} INFO - ---------------------------------------------------------------------
[2025-02-20T15:46:48.522+0000] {spark_submit.py:641} INFO - |                  |            modules            ||   artifacts   |
[2025-02-20T15:46:48.523+0000] {spark_submit.py:641} INFO - |       conf       | number| search|dwnlded|evicted|| number|dwnlded|
[2025-02-20T15:46:48.524+0000] {spark_submit.py:641} INFO - ---------------------------------------------------------------------
[2025-02-20T15:46:48.525+0000] {spark_submit.py:641} INFO - |      default     |   2   |   2   |   2   |   0   ||   2   |   2   |
[2025-02-20T15:46:48.526+0000] {spark_submit.py:641} INFO - ---------------------------------------------------------------------
[2025-02-20T15:46:48.527+0000] {spark_submit.py:641} INFO - :: retrieving :: org.apache.spark#spark-submit-parent-d36a42ef-4843-4694-8d99-f8de5bd45dd8
[2025-02-20T15:46:48.528+0000] {spark_submit.py:641} INFO - confs: [default]
[2025-02-20T15:46:48.534+0000] {spark_submit.py:641} INFO - 2 artifacts copied, 0 already retrieved (1190kB/11ms)
[2025-02-20T15:46:48.985+0000] {spark_submit.py:641} INFO - 25/02/20 15:46:48 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-02-20T15:46:49.506+0000] {spark_submit.py:641} INFO - python3: can't open file '/spark-scripts/***_v2_extract.py': [Errno 2] No such file or directory
[2025-02-20T15:46:49.519+0000] {spark_submit.py:641} INFO - 25/02/20 15:46:49 INFO ShutdownHookManager: Shutdown hook called
[2025-02-20T15:46:49.521+0000] {spark_submit.py:641} INFO - 25/02/20 15:46:49 INFO ShutdownHookManager: Deleting directory /tmp/spark-a87659a4-d391-466c-b297-cf2982e3f45f
[2025-02-20T15:46:49.602+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 177, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 567, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://***-spark-master:7077 --packages org.postgresql:postgresql:42.2.18 --name arrow-spark /spark-scripts/***_v2_extract.py. Error code is: 2.
[2025-02-20T15:46:49.616+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=***_v2_etl_dag, task_id=extract_task, run_id=manual__2025-02-20T15:46:32.551269+00:00, execution_date=20250220T154632, start_date=20250220T154636, end_date=20250220T154649
[2025-02-20T15:46:49.690+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-20T15:46:49.694+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 86 for task extract_task (Cannot execute: spark-submit --master spark://***-spark-master:7077 --packages org.postgresql:postgresql:42.2.18 --name arrow-spark /spark-scripts/***_v2_extract.py. Error code is: 2.; 403)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 177, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 567, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://***-spark-master:7077 --packages org.postgresql:postgresql:42.2.18 --name arrow-spark /spark-scripts/***_v2_extract.py. Error code is: 2.
[2025-02-20T15:46:49.719+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-20T15:46:49.753+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-20T15:46:49.760+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
