[2025-02-20T03:24:39.018+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-20T03:24:39.056+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: finprode8_v2_etl_dag.extract_task manual__2025-02-20T03:24:34.161456+00:00 [queued]>
[2025-02-20T03:24:39.082+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: finprode8_v2_etl_dag.extract_task manual__2025-02-20T03:24:34.161456+00:00 [queued]>
[2025-02-20T03:24:39.085+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-20T03:24:39.119+0000] {taskinstance.py:2889} INFO - Executing <Task(SparkSubmitOperator): extract_task> on 2025-02-20 03:24:34.161456+00:00
[2025-02-20T03:24:39.128+0000] {standard_task_runner.py:72} INFO - Started process 1821 to run task
[2025-02-20T03:24:39.136+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', '***_v2_etl_dag', 'extract_task', 'manual__2025-02-20T03:24:34.161456+00:00', '--job-id', '51', '--raw', '--subdir', 'DAGS_FOLDER/***_v2_etl_dag.py', '--cfg-path', '/tmp/tmpfg6kjizy']
[2025-02-20T03:24:39.141+0000] {standard_task_runner.py:105} INFO - Job 51: Subtask extract_task
[2025-02-20T03:24:39.178+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.9/site-packages/airflow/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-20T03:24:39.240+0000] {task_command.py:467} INFO - Running <TaskInstance: finprode8_v2_etl_dag.extract_task manual__2025-02-20T03:24:34.161456+00:00 [running]> on host ***-airflow-scheduler
[2025-02-20T03:24:39.445+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ratih malini' AIRFLOW_CTX_DAG_ID='***_v2_etl_dag' AIRFLOW_CTX_TASK_ID='extract_task' AIRFLOW_CTX_EXECUTION_DATE='2025-02-20T03:24:34.161456+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-20T03:24:34.161456+00:00'
[2025-02-20T03:24:39.450+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-20T03:24:39.534+0000] {base.py:84} INFO - Retrieving connection 'spark_main'
[2025-02-20T03:24:39.537+0000] {spark_submit.py:474} INFO - Spark-Submit cmd: spark-submit --master spark://***-spark-master:7077 --packages org.postgresql:postgresql:42.2.18 --name arrow-spark /spark-scripts/***_v2_extract.py
[2025-02-20T03:24:43.063+0000] {spark_submit.py:641} INFO - :: loading settings :: url = jar:file:/home/airflow/.local/lib/python3.9/site-packages/pyspark/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2025-02-20T03:24:43.210+0000] {spark_submit.py:641} INFO - Ivy Default Cache set to: /home/airflow/.ivy2/cache
[2025-02-20T03:24:43.212+0000] {spark_submit.py:641} INFO - The jars for the packages stored in: /home/airflow/.ivy2/jars
[2025-02-20T03:24:43.215+0000] {spark_submit.py:641} INFO - org.postgresql#postgresql added as a dependency
[2025-02-20T03:24:43.217+0000] {spark_submit.py:641} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-dfb717cc-ce2d-430d-964d-f400a9bdab39;1.0
[2025-02-20T03:24:43.219+0000] {spark_submit.py:641} INFO - confs: [default]
[2025-02-20T03:24:43.358+0000] {spark_submit.py:641} INFO - found org.postgresql#postgresql;42.2.18 in central
[2025-02-20T03:24:43.381+0000] {spark_submit.py:641} INFO - found org.checkerframework#checker-qual;3.5.0 in central
[2025-02-20T03:24:43.400+0000] {spark_submit.py:641} INFO - :: resolution report :: resolve 177ms :: artifacts dl 7ms
[2025-02-20T03:24:43.402+0000] {spark_submit.py:641} INFO - :: modules in use:
[2025-02-20T03:24:43.405+0000] {spark_submit.py:641} INFO - org.checkerframework#checker-qual;3.5.0 from central in [default]
[2025-02-20T03:24:43.406+0000] {spark_submit.py:641} INFO - org.postgresql#postgresql;42.2.18 from central in [default]
[2025-02-20T03:24:43.408+0000] {spark_submit.py:641} INFO - ---------------------------------------------------------------------
[2025-02-20T03:24:43.409+0000] {spark_submit.py:641} INFO - |                  |            modules            ||   artifacts   |
[2025-02-20T03:24:43.411+0000] {spark_submit.py:641} INFO - |       conf       | number| search|dwnlded|evicted|| number|dwnlded|
[2025-02-20T03:24:43.413+0000] {spark_submit.py:641} INFO - ---------------------------------------------------------------------
[2025-02-20T03:24:43.417+0000] {spark_submit.py:641} INFO - |      default     |   2   |   0   |   0   |   0   ||   2   |   0   |
[2025-02-20T03:24:43.419+0000] {spark_submit.py:641} INFO - ---------------------------------------------------------------------
[2025-02-20T03:24:43.422+0000] {spark_submit.py:641} INFO - :: retrieving :: org.apache.spark#spark-submit-parent-dfb717cc-ce2d-430d-964d-f400a9bdab39
[2025-02-20T03:24:43.424+0000] {spark_submit.py:641} INFO - confs: [default]
[2025-02-20T03:24:43.426+0000] {spark_submit.py:641} INFO - 0 artifacts copied, 2 already retrieved (0kB/10ms)
[2025-02-20T03:24:43.786+0000] {spark_submit.py:641} INFO - 25/02/20 03:24:43 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-02-20T03:24:45.417+0000] {spark_submit.py:641} INFO - Traceback (most recent call last):
[2025-02-20T03:24:45.419+0000] {spark_submit.py:641} INFO - File "/spark-scripts/***_v2_extract.py", line 2, in <module>
[2025-02-20T03:24:45.422+0000] {spark_submit.py:641} INFO - import kagglehub
[2025-02-20T03:24:45.424+0000] {spark_submit.py:641} INFO - ModuleNotFoundError: No module named 'kagglehub'
[2025-02-20T03:24:45.461+0000] {spark_submit.py:641} INFO - 25/02/20 03:24:45 INFO ShutdownHookManager: Shutdown hook called
[2025-02-20T03:24:45.463+0000] {spark_submit.py:641} INFO - 25/02/20 03:24:45 INFO ShutdownHookManager: Deleting directory /tmp/spark-41554f38-d0b8-46f9-8101-1fbe8b5fe3fe
[2025-02-20T03:24:45.536+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 177, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 567, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://***-spark-master:7077 --packages org.postgresql:postgresql:42.2.18 --name arrow-spark /spark-scripts/***_v2_extract.py. Error code is: 1.
[2025-02-20T03:24:45.557+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=***_v2_etl_dag, task_id=extract_task, run_id=manual__2025-02-20T03:24:34.161456+00:00, execution_date=20250220T032434, start_date=20250220T032439, end_date=20250220T032445
[2025-02-20T03:24:45.592+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-20T03:24:45.594+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 51 for task extract_task (Cannot execute: spark-submit --master spark://***-spark-master:7077 --packages org.postgresql:postgresql:42.2.18 --name arrow-spark /spark-scripts/***_v2_extract.py. Error code is: 1.; 1821)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 177, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 567, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://***-spark-master:7077 --packages org.postgresql:postgresql:42.2.18 --name arrow-spark /spark-scripts/***_v2_extract.py. Error code is: 1.
[2025-02-20T03:24:45.622+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-20T03:24:45.651+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-20T03:24:45.657+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
