[2025-02-21T07:53:22.228+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-21T07:53:22.269+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: finprode8_v2_etl_dag.transform_task manual__2025-02-21T07:31:04.105699+00:00 [queued]>
[2025-02-21T07:53:22.298+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: finprode8_v2_etl_dag.transform_task manual__2025-02-21T07:31:04.105699+00:00 [queued]>
[2025-02-21T07:53:22.301+0000] {taskinstance.py:2867} INFO - Starting attempt 4 of 4
[2025-02-21T07:53:22.349+0000] {taskinstance.py:2890} INFO - Executing <Task(SparkSubmitOperator): transform_task> on 2025-02-21 07:31:04.105699+00:00
[2025-02-21T07:53:22.362+0000] {standard_task_runner.py:72} INFO - Started process 2822 to run task
[2025-02-21T07:53:22.369+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', '***_v2_etl_dag', 'transform_task', 'manual__2025-02-21T07:31:04.105699+00:00', '--job-id', '110', '--raw', '--subdir', 'DAGS_FOLDER/***_v2_etl_dag.py', '--cfg-path', '/tmp/tmp0yaay3ip']
[2025-02-21T07:53:22.377+0000] {standard_task_runner.py:105} INFO - Job 110: Subtask transform_task
[2025-02-21T07:53:22.418+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.9/site-packages/airflow/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-21T07:53:22.545+0000] {task_command.py:467} INFO - Running <TaskInstance: finprode8_v2_etl_dag.transform_task manual__2025-02-21T07:31:04.105699+00:00 [running]> on host ***-airflow-scheduler
[2025-02-21T07:53:22.741+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ratih malini' AIRFLOW_CTX_DAG_ID='***_v2_etl_dag' AIRFLOW_CTX_TASK_ID='transform_task' AIRFLOW_CTX_EXECUTION_DATE='2025-02-21T07:31:04.105699+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-21T07:31:04.105699+00:00'
[2025-02-21T07:53:22.744+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-21T07:53:22.818+0000] {base.py:84} INFO - Retrieving connection 'spark_main'
[2025-02-21T07:53:22.823+0000] {spark_submit.py:474} INFO - Spark-Submit cmd: spark-submit --master spark://***-spark-master:7077 --packages org.postgresql:postgresql:42.2.18 --name arrow-spark /spark-scripts/***_v2_transform.py
[2025-02-21T07:53:24.834+0000] {spark_submit.py:641} INFO - :: loading settings :: url = jar:file:/home/airflow/.local/lib/python3.9/site-packages/pyspark/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2025-02-21T07:53:25.002+0000] {spark_submit.py:641} INFO - Ivy Default Cache set to: /home/airflow/.ivy2/cache
[2025-02-21T07:53:25.005+0000] {spark_submit.py:641} INFO - The jars for the packages stored in: /home/airflow/.ivy2/jars
[2025-02-21T07:53:25.011+0000] {spark_submit.py:641} INFO - org.postgresql#postgresql added as a dependency
[2025-02-21T07:53:25.013+0000] {spark_submit.py:641} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-510c4aa9-ef8b-48aa-9a45-c549a96b2d1b;1.0
[2025-02-21T07:53:25.015+0000] {spark_submit.py:641} INFO - confs: [default]
[2025-02-21T07:53:25.242+0000] {spark_submit.py:641} INFO - found org.postgresql#postgresql;42.2.18 in central
[2025-02-21T07:53:25.297+0000] {spark_submit.py:641} INFO - found org.checkerframework#checker-qual;3.5.0 in central
[2025-02-21T07:53:25.320+0000] {spark_submit.py:641} INFO - :: resolution report :: resolve 301ms :: artifacts dl 6ms
[2025-02-21T07:53:25.322+0000] {spark_submit.py:641} INFO - :: modules in use:
[2025-02-21T07:53:25.323+0000] {spark_submit.py:641} INFO - org.checkerframework#checker-qual;3.5.0 from central in [default]
[2025-02-21T07:53:25.328+0000] {spark_submit.py:641} INFO - org.postgresql#postgresql;42.2.18 from central in [default]
[2025-02-21T07:53:25.330+0000] {spark_submit.py:641} INFO - ---------------------------------------------------------------------
[2025-02-21T07:53:25.332+0000] {spark_submit.py:641} INFO - |                  |            modules            ||   artifacts   |
[2025-02-21T07:53:25.333+0000] {spark_submit.py:641} INFO - |       conf       | number| search|dwnlded|evicted|| number|dwnlded|
[2025-02-21T07:53:25.335+0000] {spark_submit.py:641} INFO - ---------------------------------------------------------------------
[2025-02-21T07:53:25.337+0000] {spark_submit.py:641} INFO - |      default     |   2   |   0   |   0   |   0   ||   2   |   0   |
[2025-02-21T07:53:25.338+0000] {spark_submit.py:641} INFO - ---------------------------------------------------------------------
[2025-02-21T07:53:25.340+0000] {spark_submit.py:641} INFO - :: retrieving :: org.apache.spark#spark-submit-parent-510c4aa9-ef8b-48aa-9a45-c549a96b2d1b
[2025-02-21T07:53:25.342+0000] {spark_submit.py:641} INFO - confs: [default]
[2025-02-21T07:53:25.344+0000] {spark_submit.py:641} INFO - 0 artifacts copied, 2 already retrieved (0kB/8ms)
[2025-02-21T07:53:25.662+0000] {spark_submit.py:641} INFO - 25/02/21 07:53:25 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-02-21T07:53:26.229+0000] {spark_submit.py:641} INFO - File "/spark-scripts/***_v2_transform.py", line 48
[2025-02-21T07:53:26.232+0000] {spark_submit.py:641} INFO - print("---------------- MENAMPILKAN BANYAK DATA NULL DI SETIAP KOLOM ----------------")
[2025-02-21T07:53:26.234+0000] {spark_submit.py:641} INFO - IndentationError: unexpected indent
[2025-02-21T07:53:26.244+0000] {spark_submit.py:641} INFO - 25/02/21 07:53:26 INFO ShutdownHookManager: Shutdown hook called
[2025-02-21T07:53:26.248+0000] {spark_submit.py:641} INFO - 25/02/21 07:53:26 INFO ShutdownHookManager: Deleting directory /tmp/spark-46dbbe2c-7af5-4467-b4f3-13d15a375872
[2025-02-21T07:53:26.339+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 177, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 567, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://***-spark-master:7077 --packages org.postgresql:postgresql:42.2.18 --name arrow-spark /spark-scripts/***_v2_transform.py. Error code is: 1.
[2025-02-21T07:53:26.365+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=***_v2_etl_dag, task_id=transform_task, run_id=manual__2025-02-21T07:31:04.105699+00:00, execution_date=20250221T073104, start_date=20250221T075322, end_date=20250221T075326
[2025-02-21T07:53:26.450+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-21T07:53:26.455+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 110 for task transform_task (Cannot execute: spark-submit --master spark://***-spark-master:7077 --packages org.postgresql:postgresql:42.2.18 --name arrow-spark /spark-scripts/***_v2_transform.py. Error code is: 1.; 2822)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 177, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 567, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://***-spark-master:7077 --packages org.postgresql:postgresql:42.2.18 --name arrow-spark /spark-scripts/***_v2_transform.py. Error code is: 1.
[2025-02-21T07:53:26.486+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-21T07:53:26.549+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-21T07:53:26.561+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
